
package com.example.Example.mernis;
//------------------------------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 9.0.1.0
//
// Created by Quasar Development 
//
// This class has been generated for test purposes only and cannot be used in any commercial project.
// To use it in commercial project, you need to generate this class again with Premium account.
// Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
//
// Licence: 656479C1301C6A31985379BCE8FAA6A9573D38C243E03EA4090CFDF98306C3CA6A9E50259376755F8643E2D1E2350132170CE870D5FABB1D765BA81123806EDE
//------------------------------------------------------------------------
import java.net.URL;
import java.io.*;
import java.net.HttpURLConnection;
import java.util.HashMap;
import java.util.Map;
import java.util.List;

public interface HWGConnectionProvider
{
    HWGResponseData sendRequest(String url,String requestBody,HashMap< String,String> httpHeaders, HWGRequestResultHandler handler) throws Exception;
}

class HWGHttpConnectionProvider implements HWGConnectionProvider{

    public void prepareRequest(HttpURLConnection url,String requestBody, HWGRequestResultHandler handler) throws Exception {
        OutputStreamWriter wr = new OutputStreamWriter(url.getOutputStream());
        wr.write(requestBody);
        wr.flush();
    }

    @Override
    public HWGResponseData sendRequest(String url,String requestBody, HashMap< String, String> httpHeaders,HWGRequestResultHandler handler ) throws Exception
    {
        URL urlObject=new URL(url);
        HttpURLConnection connection=(HttpURLConnection)urlObject.openConnection();
        connection.setRequestMethod("POST");
        connection.setDoOutput(true);
        for(Map.Entry<String, String> entry : httpHeaders.entrySet())
        {
            connection.setRequestProperty(entry.getKey(),entry.getValue());
        }

        prepareRequest(connection,requestBody,handler);


        HWGResponseData response=new HWGResponseData();
        for(Map.Entry<String, List<String>> entry : connection.getHeaderFields().entrySet())
        {
            if(entry.getKey()!=null)
            {
                String values = "";
                for (String value : entry.getValue()) {
                    values = values + value;
                }
                response.getHeaders().put(entry.getKey(),values);
            }
        }
        
        try(InputStream dataStream = getResponseStream(connection,response,handler))
        {
            response.setBody(HWGHelper.streamToString(dataStream));
        }
        
        return response;
    }

    protected InputStream getResponseStream(
        HttpURLConnection url,
        HWGResponseData response,
        HWGRequestResultHandler handler
    ) throws Exception
    {
        try{
            return url.getInputStream();
        }
        catch (IOException ex)
        {
            return url.getErrorStream();
        }
    }
}