

package com.example.Example.mernis;
//------------------------------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 9.0.1.0
//
// Created by Quasar Development 
//
// This class has been generated for test purposes only and cannot be used in any commercial project.
// To use it in commercial project, you need to generate this class again with Premium account.
// Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
//
// Licence: 656479C1301C6A31985379BCE8FAA6A9573D38C243E03EA4090CFDF98306C3CA6A9E50259376755F8643E2D1E2350132170CE870D5FABB1D765BA81123806EDE
//------------------------------------------------------------------------

public class HWGSoapException extends Exception
{
    private org.w3c.dom.Element _details=null;
    private Object _fault = null;
    
    public HWGSoapException(String message,org.w3c.dom.Element details)
    {
        super(message);
        _details=details;
    }

    public HWGSoapException(Object fault)
    {
        _fault=fault;
    }

    public Object getFault() {
        return _fault;
    }


    public org.w3c.dom.Element getDetails() {
        return _details;
    }
}